version: '3.1'

services:
    nextjs:
        ports:
            - 8080:3000
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PROTOCOL: http
            HOSTNAME: metajob
            NEXTJS_PORT: 3000
            PUBLIC_PORT: 8080